release-date = "2022-03-17"

[[entries]]
id = "0922059c-e19b-4743-8e29-3240ecfaa82b"
type = "breaking change"
description = "Change `ForwardRef` and `NewType` to hold the origin `typing` object"
author = "@NiklasRosenstein"

[[entries]]
id = "eab7b8bd-7805-4b33-8dae-ba17dd3cdb0b"
type = "feature"
description = "Implement `ForwardRef.evaluate()`"
author = "@NiklasRosenstein"

[[entries]]
id = "f0d0e72e-ae25-4f32-823c-18d92cd447a6"
type = "feature"
description = "add `typeapi.eval_types()`"
author = "@NiklasRosenstein"

[[entries]]
id = "5330906d-bac4-4cef-a572-052244283334"
type = "feature"
description = "add `typeapi.infuse_type_parameters()`"
author = "@NiklasRosenstein"
