release-date = "2022-03-17"

[[entries]]
id = "ac6fa5da-cc82-42fd-ae05-df8ef1ae1fed"
type = "fix"
description = "fix `from typeapi import *`"
author = "@NiklasRosenstein"

[[entries]]
id = "8e0d6f68-83f3-43bc-8899-360f2b90e9d5"
type = "improvement"
description = "export `get_type_hints()` and `type_repr()` in `typeapi` root module"
author = "@NiklasRosenstein"

[[entries]]
id = "a322f92a-39ac-4236-b280-4980974cbb0e"
type = "improvement"
description = "`is_generic()` no longer returns true if the type is the actualy `typing.Generic` because only its subclasses of `__parameters__`"
author = "@NiklasRosenstein"

[[entries]]
id = "af69ca3f-c50a-4c3a-80f8-4d46197e2587"
type = "fix"
description = "`Type.of()` no longer errors on passing `typing.Generic` and handles it as `Type(typing.Generic, 0, None, None)`"
author = "@NiklasRosenstein"

[[entries]]
id = "ce02d673-8dd8-4301-95f6-234a5134bb4c"
type = "feature"
description = "Add `Type.get_parameter_mapping()`"
author = "@NiklasRosenstein"

[[entries]]
id = "bb1c3753-1fd0-4b27-a713-eb746a4c7e93"
type = "breaking change"
description = "Type hints are now converted recursively, all recursive API models now store `Hint` objects directly instead of the raw typing argument."
author = "@NiklasRosenstein"
